# Generated by Django 6.1.1 on 2026-09-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, default='media/default/new.jpg', null=True, upload_to='media/'),
        ),
    ]
